#! /bin/bash
# @author jonas.eberle@aero.de / flightvision@googlemail.com

THIS=$(readlink -f $0)
CONF=/etc/backup_hardlink.conf
LOG=/var/log/$(basename $THIS _wrapper).log
# ionice -c 3 : idle i/o
# nice : nice += 10


LOCKFILE=/var/lock/backup_hardlink
{       
	if ! flock -n 9; then
		#echo "Unable to lock $LOCKFILE, exiting" 2>&1
		exit 1
	fi
				
	# remove lockfile
	trap "rm $LOCKFILE 2> /dev/null" EXIT INT KILL TERM
			        
	# Error with --compress"
	EXEC="$(dirname $THIS)/$(basename $THIS _wrapper) $CONF --partial --progress --verbose"
	ionice -c 2 -n 7 nice $EXEC >> $LOG 2>&1

	EXEC="$(dirname $THIS)/$(basename $THIS _wrapper)_cleaner $CONF"

	ionice -c 2 -n 7 nice $EXEC >> $LOG 2>&1
	exit $?
} 9>"$LOCKFILE"

